### ISSUE TITLE
get mail failling because too long value

### ISSUE THREAD

**Issue by RafaelOrtiz** [rossp/django-helpdesk#327]
I'm using the upstream get_email command:

Trace is something like: 
python manage.py get_email     
Processing: queue
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/www/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/srv/www/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/www/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/srv/zinalat-pack/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/srv/zinalat-pack/lib/python2.7/site-packages/helpdesk/management/commands/get_email.py", line 60, in handle
    process_email(quiet=quiet)
  File "/srv/zinalat-pack/lib/python2.7/site-packages/helpdesk/management/commands/get_email.py", line 80, in process_email
    process_queue(q, quiet=quiet)
  File "/srv//lib/python2.7/site-packages/helpdesk/management/commands/get_email.py", line 136, in process_queue
    ticket = ticket_from_message(message=data[0][1], queue=q, quiet=quiet)
  File "/srv/www//lib/python2.7/site-packages/helpdesk/management/commands/get_email.py", line 276, in ticket_from_message
    t.save()
  File "/srv/www//lib/python2.7/site-packages/helpdesk/models.py", line 468, in save
    super(Ticket, self).save(*args, **kwargs)
  File "/srv/www/lib/python2.7/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/srv/www/lib/python2.7/site-packages/django/db/models/base.py", line 617, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/srv/www//lib/python2.7/site-packages/django/db/models/base.py", line 698, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/srv/www/zinalat-pack/lib/python2.7/site-packages/django/db/models/base.py", line 731, in _do_insert
    using=using, raw=raw)
  File "/srv/www/zinalat-pack/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/srv/www/zinalat-pack/lib/python2.7/site-packages/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/srv/www/zinalat-pack/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 920, in execute_sql
    cursor.execute(sql, params)
  File "/srv/www/zinalat-pack/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/srv/www/zinalat-pack/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/srv/www//lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: value too long for type character varying(200)

**Comment by RafaelOrtiz** [comment]
btw if anyone happens to encounter this error...I manage to fix it augmenting..the max_length of this model...https://github.com/RafaelOrtiz/django-helpdesk/commit/d9ae716e7c8451607547f6bc98818ca3ef0ac34c   (just documenting the solution here..but this commit is not suitable for production).
