### ISSUE TITLE
Database migration with django 1.7+

### ISSUE THREAD

**Issue by FabriceSalvaire** [rossp/django-helpdesk#339]
I am trying to setup django-helpdesk with django 1.8, the command

`python manage.py migrate helpdesk`

raises an import error for south. But south is deprecated for django 1.7.  Moreover the manual says south is optional.

**Comment by reduxionist** [comment]
Django 1.8 compatibility is a work in progress, I hope to be submitting a PR for review soon.

In the meantime, you might want to check @flinz’s fork for the most comprehensive Django 1.8 branch to date.

Other than that, a common cause of these problems is missing/inactive virtual environments. Please try with Django 1.7 in a clean new virtualenv and if the problem persists please attach the install logs and exact error message + traceback you receive. Thanks.

**Comment by FabriceSalvaire** [comment]
First problem, `pip install django-helpdesk` in a fresh virtualenv will install django 1.8

Then `python manage.py syncdb` yields

<pre>
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/python-virtual-env/py3-django-helpdesk/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/opt/python-virtual-env/py3-django-helpdesk/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/opt/python-virtual-env/py3-django-helpdesk/lib/python3.4/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/python-virtual-env/py3-django-helpdesk/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/opt/python-virtual-env/py3-django-helpdesk/lib/python3.4/site-packages/django/apps/config.py", line 87, in create
    module = import_module(entry)
  File "/opt/python-virtual-env/py3-django-helpdesk/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'south'
</pre>

and install south is useless since

<pre>RuntimeError: South does not support Django 1.7 or higher. Please use native Django migrations.</pre>

**Comment by flinz** [comment]
You probably have ``south`` as an entry in your ``INSTALLED_APPS`` in ``settings.py``. 
If you comment that line it should work.

**Comment by rossp** [comment]
This should be closed given recent updates for Django 1.9 (see #351, #355). Removing `south` should also help, please re-open if this is still an issue.
