### ISSUE TITLE
creating a new user by django-admin

### ISSUE THREAD

**Issue by i25** [rossp/django-helpdesk#347]
OperationalError at /admin/auth/user/add/

no such table: helpdesk_usersettings

**Comment by flinz** [comment]
Did you run ``./manage.py migrate helpdesk`` and ``./manage.py syncdb``?
https://github.com/rossp/django-helpdesk/blob/master/docs/install.rst

**Comment by i25** [comment]
manage.py@srit > migrate helpdesk
bash -cl "/usr/bin/python3.4 /home/pradeep/Desktop/pycharm-4.5.3/helpers/pycharm/django_manage.py migrate helpdesk /home/pradeep/Desktop/srit"
System check identified some issues:

WARNINGS:
helpdesk.EscalationExclusion.queues: (fields.W340) null has no effect on ManyToManyField.
helpdesk.IgnoreEmail.queues: (fields.W340) null has no effect on ManyToManyField.
helpdesk.PreSetReply.queues: (fields.W340) null has no effect on ManyToManyField.
Operations to perform:
  Apply all migrations: helpdesk
Running migrations:
  Rendering model states... DONE
  Applying helpdesk.0001_initial...Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/sqlite3/base.py", line 316, in execute
    return Database.Cursor.execute(self, query)
sqlite3.OperationalError: near "b": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pradeep/Desktop/pycharm-4.5.3/helpers/pycharm/django_manage.py", line 41, in <module>
    run_module(manage_file, None, '__main__', True)
  File "/usr/lib/python3.4/runpy.py", line 182, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pradeep/Desktop/srit/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/operations/models.py", line 59, in database_forwards
    schema_editor.create_model(model)
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/base/schema.py", line 286, in create_model
    self.execute(sql, params or None)
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.4/dist-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/sqlite3/base.py", line 316, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: near "b": syntax error

Process finished with exit code 1

**Comment by flinz** [comment]
What's your django version? ``./manage.py version``

**Comment by i25** [comment]
Django 1.8.5

**Comment by rossp** [comment]
I *think* this might be due to your use of Python 3. Unfortunately I haven't been able to test on py3 for various reasons sorry which isn't really good enough for the end of 2015... 

Can anybody following this confirm use of Python 3 with django-helpdesk?

**Comment by rossp** [comment]
Note other Python 3 issues slowly gathering at #290 - need to address this properly.

**Comment by i25** [comment]
yes , i have uninstall Python3.4 and now Python 2.7 install everything working fine only one issue remains.
 "RelatedObjectDoesNotExist at /helpdesk/tickets/submit/
User has no usersettings."

Please help me

**Comment by i25** [comment]
Thanks a lot problem resolved and helpdesk working properly
