### ISSUE TITLE
Error in testsuite: RelatedObjectDoesNotExist: User has no queuemembership.

### ISSUE THREAD

**Issue by flinz** [rossp/django-helpdesk#353]
This is probably for @reduxionist.

Testing helpdesk via ``quicktest.py`` passes all tests.

However running the testsuite via 
```python manage.py test helpdesk```
gives me a weird error (trace is below) probably related to the staff per queue membership feature.

This is raised in ``test_navigation`` around ``82: queue__in=request.user.queuemembership.queues.all()``. I tried fiddling with the test settings and enabling/disabling ``HELPDESK_ENABLE_PER_QUEUE_STAFF_MEMBERSHIP``, to no avail. 

Since this does NOT occur when testing via ``quicktest.py`` I am bit puzzled - has to do something with the test environments probably. Maybe somebody has some ideas.

------------

```python
Traceback (most recent call last):
  File "django-helpdesk/helpdesk/tests/test_navigation.py", line 31, in test_navigation
    response = self.client.get(reverse('helpdesk_dashboard'))
  File "/Users/username/.virtualenvs/test_dj18/lib/python2.7/site-packages/django/test/client.py", line 500, in get
    **extra)
  File "/Users/username/.virtualenvs/test_dj18/lib/python2.7/site-packages/django/test/client.py", line 303, in get
    return self.generic('GET', path, secure=secure, **r)
  File "/Users/username/.virtualenvs/test_dj18/lib/python2.7/site-packages/django/test/client.py", line 379, in generic
    return self.request(**r)
  File "/Users/username/.virtualenvs/test_dj18/lib/python2.7/site-packages/django/test/client.py", line 466, in request
    six.reraise(*exc_info)
  File "/Users/username/.virtualenvs/test_dj18/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/username/.virtualenvs/test_dj18/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "django-helpdesk/helpdesk/views/staff.py", line 82, in dashboard
    queue__in=request.user.queuemembership.queues.all(),
  File "/Users/username/.virtualenvs/test_dj18/lib/python2.7/site-packages/django/utils/functional.py", line 226, in inner
    return func(self._wrapped, *args)
  File "/Users/username/.virtualenvs/test_dj18/lib/python2.7/site-packages/django/db/models/fields/related.py", line 470, in __get__
    self.related.get_accessor_name()
RelatedObjectDoesNotExist: User has no queuemembership.
```

**Comment by reduxionist** [comment]
@flinx Thanks for letting me know, I'm looking into it right now, and have a strong suspicion as to what the cause is, so there's no need for you to investigate any further.  :)
