### ISSUE TITLE
RuntimeError: Model class helpdesk.models.Queue doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS

### ISSUE THREAD

**Issue by jdoer1997** [rossp/django-helpdesk#389]
Hi

I've installed (using pip) django-helpdesk on a Django 1.9.3, Python 3.4 instance (which also runs Mezzanine).  When I run "python3 manage.py migrate helpdesk", I get the traceback below.
Any help or suggestion appreciated.

Traceback (most recent call last):
  File "/opt/wsgi/myco/manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 398, in execute
    self.check()
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 23, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/opt/wsgi/myco/urls.py", line 34, in <module>
    url(r'helpdesk/', include('helpdesk.urls')),
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 52, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/usr/local/lib/python3.4/dist-packages/helpdesk/urls.py", line 19, in <module>
    from helpdesk.views import feeds, staff, public, api, kb
  File "/usr/local/lib/python3.4/dist-packages/helpdesk/views/feeds.py", line 21, in <module>
    from helpdesk.models import Ticket, FollowUp, Queue
  File "/usr/local/lib/python3.4/dist-packages/helpdesk/models.py", line 30, in <module>
    class Queue(models.Model):
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/base.py", line 102, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class helpdesk.models.Queue doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

**Comment by jdoer1997** [comment]
Mezzanine has a settings.py and a local_settings.py.  I could get past this problem  by adding the following to  INSTALLED_APPS in local_settings.py instead of to settings.py:

   "django.contrib.humanize",
    "markdown_deux",
    "bootstrapform",
    "helpdesk",
